import * as _ from "lodash"

export default {
    chunk         : _.chunk
  , compact       : _.compact
  , concat        : _.concat
  , drop          : _.drop
  , dropRight     : _.dropRight
  , fill          : _.fill
  , flatten       : _.flatten
  , flattenDeep   : _.flattenDeep
  , FromPairs     : _.FromPairs
  , head          : _.head
  , first         : _.first
  , tial          : _.tial
  , indexOf       : _.indexOf
  , join          : _.join
  , last          : _.last
  , nth           : _.nth
  , reverse       : _.reverse
  , slice         : _.slice
  , take          : _.take
  , takeRight     : _.takeRight
  , takeWhile     : _.takeWhile
  , takeRightWhile: _.takeRightWhile
  , union         : _.union
  , uniq          : _.uniq
  , uniqBy        : _.uniqBy
  , uniqWith      : _.uniqWith
  , without       : _.without
  , xor           : _.xor
  , every         : _.every
  , filter        : _.filter
  , find          : _.find
  , flatMap       : _.flatMap
  , flatMapDeep   : _.flatMapDeep
  , each          : _.each
  , eachRight     : _.eachRight
  , groupBy       : _.groupBy
  , includes      : _.includes
  , map           : _.map
  , reduce        : _.reduce
  , reduceRight   : _.reduceRight
  , reject        : _.reject
  , sample        : _.sample
  , orderBy       : _.orderBy
  , shuffle       : _.shuffle
  , size          : _.size
  , some          : _.some
  , sortBy        : _.sortBy
  , now           : _.now
  , after         : _.after
  , before        : _.before
  , curry         : _.curry
  , curryRight    : _.curryRight
  , flip          : _.flip
  , negate        : _.negate
  , once          : _.once
  , castArray     : _.castArray
  , clone         : _.clone
  , eq            : _.eq
  , gt            : _.gt
  , lt            : _.lt
  , gte           : _.gte
  , lte           : _.lte
  , isArray       : _.isArray
  , isArrayLike   : _.isArrayLike
  , isBoolean     : _.isBoolean
  , isDate        : _.isDate
  , isEmpty       : _.isEmpty
  , isEqual       : _.isEqual
  , isFinite      : _.isFinite
  , isFunction    : _.isFunction
  , isInteger     : _.isInteger
  , isNull        : _.isNull
  , isNumber      : _.isNumber
  , isObject      : _.isObject
  , isObjectLike  : _.isObjectLike
  , isPlainObject : _.isPlainObject
  , isRegExp      : _.isRegExp
  , isString      : _.isString
  , isSymbol      : _.isSymbol
  , toArray       : _.toArray
  , toInteger     : _.toInteger
  , toNumber      : _.toNumber
  , toPlainObject : _.toPlainObject
  , toString      : _.toString
  , add           : _.add
  , ceil          : _.ceil
  , divide        : _.divide
  , floor         : _.floor
  , max           : _.max
  , maxBy         : _.maxBy
  , mean          : _.mean
  , meanBy        : _.meanBy
  , min           : _.min
  , minBy         : _.minBy
  , multiply      : _.multiply
  , round         : _.round
  , subtract      : _.subtract
  , sum           : _.sum
  , sumBy         : _.sumBy
  , clamp         : _.clamp
  , inRange       : _.inRange
  , random        : _.random
  , assign        : _.assign
  , extend        : _.extend
  , at            : _.at
  , create        : _.create
  , defaults      : _.defaults
  , defaultsDeep  : _.defaultsDeep
  , findKey       : _.findKey
  , get           : _.get
  , has           : _.has
  , hasIn         : _.hasIn
  , invert        : _.invert
  , invertBy      : _.invertBy
  , invoke        : _.invoke
  , keys          : _.keys
  , merge         : _.merge
  , omit          : _.omit
  , omitBy        : _.omitBy
  , pick          : _.pick
  , pickBy        : _.pickBy
  , result        : _.result
  , set           : _.set
  , toPairs       : _.toPairs
  , transform     : _.transform
  , unset         : _.unset
  , values        : _.values
  , tap           : _.tap
  , camelCase     : _.camelCase
  , capitalize    : _.capitalize
  , deburr        : _.deburr
  , endsWith      : _.endsWith
  , excape        : _.excape
  , excapeRegExp  : _.excapeRegExp
  , kebabCase     : _.kebabCase
  , lowerCase     : _.lowerCase
  , lowerFirst    : _.lowerFirst
  , pad           : _.pad
  , padEnd        : _.padEnd
  , padStart      : _.padStart
  , parseInt      : _.parseInt
  , repeat        : _.repeat
  , replace       : _.replace
  , snakeCase     : _.snakeCase
  , split         : _.split
  , startCase     : _.startCase
  , startsWith    : _.startsWith
  , toLower       : _.toLower
  , toUpper       : _.toUpper
  , trim          : _.trim
  , trimEnd       : _.trimEnd
  , trimStart     : _.trimStart
  , truncate      : _.truncate
  , unescape      : _.unescape
  , upperCase     : _.upperCase
  , upperFirst    : _.upperFirst
  , words         : _.words
  , times         : _.times
  , stubArray     : _.stubArray
  , stubObject    : _.stubObject
  , stubFlase     : _.stubFlase
  , stubString    : _.stubString
  , stubTrue      : _.stubTrue
  , uniqueId      : _.uniqueId
  , template      : function(val, tmp) {
    return _.template(tmp)(val)
  }
}

